### Pandas and SQL Basics

This week, our goal is to build a strong foundation for future work. To achieve this, we need to understand the following key concepts:

- How we retrieve data – Understanding different data sources (e.g., CSV files, databases, APIs) and how to load data into our environment.
- How we query data – Learning how to filter, select, and manipulate data using tools such as SQL queries and Pandas operations.
- What libraries we use – Becoming familiar with essential Python libraries like Pandas for data manipulation and database connectors (e.g., sqlite3, SQLAlchemy) for working with SQL databases.

This foundational knowledge will enable us to efficiently access, analyze, and manage data in future projects.

## Pandas

In [1]:
# import the library
import pandas as pd

### Loading Different Data formats using pandas

Pandas is a powerful Python library for data manipulation and analysis. One of its key features is the ability to load data from various formats easily. Here’s how you can work with common data formats

```python
df = pd.read_csv("data.csv")  # Load a CSV file
df = pd.read_excel("data.xlsx", sheet_name="Sheet1")  # Load a specific sheet
df = pd.read_json("data.json")  # Load data from JSON format

```

Key Notes:
- Pandas automatically converts data into a DataFrame, which is a table-like structure.
- You can preview the data using df.head() to see the first few rows.
- Most functions support options like specifying delimiters (sep), encoding (encoding), and handling missing values

In [2]:
data = pd.read_csv("Smartphone_Usage_Productivity_Dataset_50000.csv")

### Overview of your data

Once you load a CSV file into a Pandas DataFrame, it’s important to understand the structure and content of your data before performing any analysis. Here’s a step-by-step overview:

To view the first 5 rows of your data you will use *data.head()* and to view the last five you use *data.tail()*

In [3]:
## Previewing the data
data.head()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
0,U1,58,Male,Professional,Android,1.3,6.7,6,8.8,4,42,1,8.7
1,U2,25,Male,Professional,Android,1.2,1.5,5,6.4,1,51,3,5.1
2,U3,19,Male,Student,iOS,5.3,5.7,5,9.0,4,14,5,6.3
3,U4,35,Female,Business Owner,iOS,5.8,2.5,2,5.7,3,36,6,12.8
4,U5,33,Male,Freelancer,Android,7.9,1.3,4,5.7,3,37,5,9.9

In [4]:
data.tail()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
49995,U49996,44,Male,Business Owner,Android,5.9,5.4,5,6.6,1,11,5,3.0
49996,U49997,42,Other,Business Owner,Android,2.9,7.4,9,6.3,2,20,4,6.2
49997,U49998,27,Female,Freelancer,iOS,1.4,2.5,4,6.7,9,39,4,5.1
49998,U49999,41,Female,Business Owner,iOS,8.9,3.0,6,5.5,2,51,0,9.2
49999,U50000,46,Other,Freelancer,Android,8.8,2.8,3,5.4,1,54,5,6.9

We always need to know the size of our data and for dat we use *data.shape* which will show us the following:
- number of rows
- number of columns

In [5]:
data.shape

(50000, 13)

Sometimes the data has so many attributes that we cant just see all of them by viewing the first five rows so we use *data.columns* to list all of the features/attributes in our data

In [6]:
data.columns

Index(['User_ID', 'Age', 'Gender', 'Occupation', 'Device_Type',
       'Daily_Phone_Hours', 'Social_Media_Hours', 'Work_Productivity_Score',
       'Sleep_Hours', 'Stress_Level', 'App_Usage_Count',
       'Caffeine_Intake_Cups', 'Weekend_Screen_Time_Hours'],
      dtype='object')

Understanding Data Types in Your Dataset

When working with data , it’s important to know the types of data you have because it affects how you analyze and manipulate it. Most datasets include three main types:
1. Categorical Data
   -  Represents discrete labels or categories.
   - Examples: Gender (Male/Female), Country (South Africa, USA), Product Type (A, B, C).
   - Often stored as strings (object) in Pandas, but can also be converted to category type for efficiency.


2. Numeric Data
  -  Represents numbers, either integers or floats.
  -  Examples: Age (25, 30), Salary (50000.0, 75000.5), Temperature (23.5).
  -  Used for calculations, statistics, and plotting.

3. Datetime Data
    - Represents dates and times.
    - Examples: 2026-02-26, 2026-02-26 14:30:00.
    - Important for time series analysis, sorting, and filtering by dates.

In [7]:
data.dtypes

User_ID                       object
Age                            int64
Gender                        object
Occupation                    object
Device_Type                   object
Daily_Phone_Hours            float64
Social_Media_Hours           float64
Work_Productivity_Score        int64
Sleep_Hours                  float64
Stress_Level                   int64
App_Usage_Count                int64
Caffeine_Intake_Cups           int64
Weekend_Screen_Time_Hours    float64
dtype: object

Get Basic Statistics
- Summary statistics for numeric columns using *data.describe()*

In [8]:
data.describe()

,Age,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000
mean,39.034960,6.509116,4.267250,5.503760,6.497744,5.504500,32.43898,3.004580,8.006844
std,12.414877,3.170903,2.164743,2.874806,1.449551,2.871095,16.12151,1.996657,3.461300
min,18.000000,1.000000,0.500000,1.000000,4.000000,1.000000,5.00000,0.000000,2.000000
25%,28.000000,3.800000,2.400000,3.000000,5.200000,3.000000,18.00000,1.000000,5.000000
50%,39.000000,6.500000,4.300000,5.500000,6.500000,6.000000,32.00000,3.000000,8.000000
75%,50.000000,9.200000,6.100000,8.000000,7.800000,8.000000,46.00000,5.000000,11.000000
max,60.000000,12.000000,8.000000,10.000000,9.000000,10.000000,60.00000,6.000000,14.000000

Handling Missing Data
- When recording or collecting data, it’s common for some entries to be missing. Missing data can cause errors or inaccurate analysis if not handled properly.
- In Pandas, you can easily check for missing values using *data.isnull().sum*

In [9]:
data.isnull().sum()

User_ID                      0
Age                          0
Gender                       0
Occupation                   0
Device_Type                  0
Daily_Phone_Hours            0
Social_Media_Hours           0
Work_Productivity_Score      0
Sleep_Hours                  0
Stress_Level                 0
App_Usage_Count              0
Caffeine_Intake_Cups         0
Weekend_Screen_Time_Hours    0
dtype: int64

Count occurrences of values
*data['column_name'].value_counts()*

In [10]:
data["Gender"].value_counts()

Gender
Male      16708
Female    16679
Other     16613
Name: count, dtype: int64

Doing this gives you a clear picture of your dataset, helping you identify missing values, data types, and potential issues before analysis.

## SQL Basics

SQL (Structured Query Language) is the standard language used to interact with relational databases like PostgreSQL. It allows you to retrieve, insert, update, and delete data in a structured way.

Selecting Data

Retrieve data from a table using SELECT

```SQL
-- Select all columns
SELECT * FROM employees;

-- Select specific columns
SELECT name, age, salary FROM employees;

```
Filtering Data

Use WHERE to filter rows based on conditions.
```SQL
SELECT * FROM employees
WHERE age > 30;

SELECT * FROM employees
WHERE department = 'Sales';

```
Sorting Data

Use ORDER BY to sort results.

```SQL
SELECT * FROM employees
ORDER BY salary DESC;  -- Descending order
```

Aggregating Data

Use functions like COUNT, SUM, AVG, MIN, MAX.

```SQL
SELECT COUNT(*) FROM employees;       -- Total employees
SELECT AVG(salary) FROM employees;    -- Average salary
SELECT MIN(age), MAX(age) FROM employees; -- Youngest & oldest
```

### How to use pandas with PostgreSQL
Pandas can directly interact with PostgreSQL databases, allowing you to query data and load it into a DataFrame for analysis. This is very useful when working with real datasets stored in a database.

In [25]:
from sqlalchemy import create_engine

Connected successfully!

In [30]:
engine = create_engine(
    "postgresql+psycopg2://username:password@127.0.0.1:5432/database"
)

In [31]:
try:
    conn = engine.connect()
    print("SQLAlchemy connection successful!")
    conn.close()
except Exception as e:
    print("Connection failed:", e)

SQLAlchemy connection successful!

In [32]:
df = pd.read_sql("SELECT * FROM film;", engine)

In [33]:
df.head()

,film_id,title,description,release_year,language_id,rental_duration,rental_rate,length,replacement_cost,rating,last_update,special_features,fulltext
0,133,Chamber Italian,A Fateful Reflection of a Moose And a Husband ...,2006,1,7,4.99,117,14.99,NC-17,2013-05-26 14:50:58.951,[Trailers],'chamber':1 'fate':4 'husband':11 'italian':2 ...
1,384,Grosse Wonderful,A Epic Drama of a Cat And a Explorer who must ...,2006,1,5,4.99,49,19.99,R,2013-05-26 14:50:58.951,[Behind the Scenes],'australia':18 'cat':8 'drama':5 'epic':4 'exp...
2,8,Airport Pollock,A Epic Tale of a Moose And a Girl who must Con...,2006,1,6,4.99,54,15.99,R,2013-05-26 14:50:58.951,[Trailers],'airport':1 'ancient':18 'confront':14 'epic':...
3,98,Bright Encounters,A Fateful Yarn of a Lumberjack And a Feminist ...,2006,1,4,4.99,73,12.99,PG-13,2013-05-26 14:50:58.951,[Trailers],'boat':20 'bright':1 'conquer':14 'encount':2 ...
4,1,Academy Dinosaur,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,6,0.99,86,20.99,PG,2013-05-26 14:50:58.951,"[Deleted Scenes, Behind the Scenes]",'academi':1 'battl':15 'canadian':20 'dinosaur...